name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Check for code formatting issues
      run: dotnet format --verify-no-changes
      continue-on-error: true  # optionally fail if formatting is bad

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run basic syntax check (build ensures this)
      run: echo "Build successful, syntax check passed."

    # Optional: Run tests if you have any
    # - name: Run tests
    #   run: dotnet test --no-build --verbosity normal
